language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
  - FLASK_ENV="PRODUCTION"
# command to run tests
script:
  - python -m pytest --cov
after success:
  - coveralls
notifications:
  email:
    recipients:
      - mikeanguandia@yahoo.com
      - anguamike@yahoo.com
